// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=139.219.100.138;uid=sa;pwd=1qaz2wsx3edc,;database=Ourtm;Connection Timeout=5;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace WeProject.Entity
{
    /// <summary>
    /// A class which represents the Attachment table.
    /// </summary>
	[Table("Attachment")]
	public partial class Attachment
	{
        /// <summary>
        /// 主键Guid
        /// </summary>
        [Key]
        public virtual Guid AttachmentId { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 文件名：201709
        /// </summary>
        public virtual string Folder { get; set; }
        /// <summary>
        /// 文件名称
        /// </summary>
        public virtual string Title { get; set; }
        /// <summary>
        /// 源文件大小
        /// </summary>
        public virtual long SizeOriginal { get; set; }
        /// <summary>
        /// 小缩略图大小
        /// </summary>
        public virtual long SizeSmall { get; set; }
        /// <summary>
        /// 大缩略图大小
        /// </summary>
        public virtual long SizeBig { get; set; }
        /// <summary>
        /// 文件扩展名
        /// </summary>
        public virtual string FileExt { get; set; }
        /// <summary>
        /// 下载量
        /// </summary>
        public virtual int Downloads { get; set; }
        /// <summary>
        /// 状态：0上传文件（超24小时就删除）；1可用的文件；2标志为不可用文件（保留系统文件，不会删除）
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DynamicMsg table.
    /// </summary>
	[Table("DynamicMsg")]
	public partial class DynamicMsg
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long DynamicMsgId { get; set; }
        /// <summary>
        /// 1组织架构；2项目；3群组；4任务
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 组织架构Id、项目Id、群组Id、任务Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 组织架构Guid、项目Guid、群组Guid、任务Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 动态消息类型
        /// </summary>
        public virtual int DynamicMsgTypeId { get; set; }
        /// <summary>
        /// 消息摘要
        /// </summary>
        public virtual string JsonSummary { get; set; }
        /// <summary>
        /// 消息详情
        /// </summary>
        public virtual string JsonDetail { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DynamicMsgType table.
    /// </summary>
	[Table("DynamicMsgType")]
	public partial class DynamicMsgType
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual int DynamicMsgTypeId { get; set; }
        /// <summary>
        /// 1组织架构；2项目；3群组；4任务
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 动态消息类型名称
        /// </summary>
        public virtual string DynamicMsgTypeName { get; set; }
	}

    /// <summary>
    /// A class which represents the Group table.
    /// </summary>
	[Table("Group")]
	public partial class Group
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long GroupId { get; set; }
        /// <summary>
        /// 主键Guid
        /// </summary>
        public virtual Guid GroupGuid { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 组名
        /// </summary>
        public virtual string GroupName { get; set; }
        /// <summary>
        /// 修改前组名
        /// </summary>
        public virtual string GroupOldName { get; set; }
        /// <summary>
        /// 状态：0正常；1已删除到回收站；2彻底删除
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 隶属于：0自己；1团队；
        /// </summary>
        public virtual int BelongTo { get; set; }
        /// <summary>
        /// 可见范围：0自己可见（本团队可见）；1本团队和上级可见；2全公司可见；
        /// </summary>
        public virtual int VisibleRange { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ObjectType table.
    /// </summary>
	[Table("ObjectType")]
	public partial class ObjectType
	{
        /// <summary>
        /// 1组织架构；2项目；3群组；4任务
        /// </summary>
        [Key]
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 容器名称
        /// </summary>
        public virtual string ObjectTypeName { get; set; }
	}

    /// <summary>
    /// A class which represents the Project table.
    /// </summary>
	[Table("Project")]
	public partial class Project
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long ProjectId { get; set; }
        /// <summary>
        /// 主键Guid
        /// </summary>
        public virtual Guid ProjectGuid { get; set; }
        /// <summary>
        /// 公司
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 项目名称
        /// </summary>
        public virtual string ProjectName { get; set; }
        /// <summary>
        /// 修改前名称
        /// </summary>
        public virtual string ProjectOldName { get; set; }
        /// <summary>
        /// 开始日期
        /// </summary>
        public virtual DateTime? BeginDate { get; set; }
        /// <summary>
        /// 结束日期
        /// </summary>
        public virtual DateTime? EndDate { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// 状态：0正常；1已删除到回收站；2彻底删除
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 隶属于：0自己；1团队；
        /// </summary>
        public virtual int BelongTo { get; set; }
        /// <summary>
        /// 可见范围：0自己可见（本团队可见）；1本团队和上级可见；2全公司可见；
        /// </summary>
        public virtual int VisibleRange { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the RoleType table.
    /// </summary>
	[Table("RoleType")]
	public partial class RoleType
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual int RoleTypeId { get; set; }
        /// <summary>
        /// 角色名称
        /// </summary>
        public virtual string RoleTypeName { get; set; }
        /// <summary>
        /// 角色简称
        /// </summary>
        public virtual string RoleTypeShortName { get; set; }
        /// <summary>
        /// 角色描述
        /// </summary>
        public virtual string RoleTypeDescription { get; set; }
	}

    /// <summary>
    /// A class which represents the TaskItem table.
    /// </summary>
	[Table("TaskItem")]
	public partial class TaskItem
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long TaskItemId { get; set; }
        /// <summary>
        /// 主键Guid
        /// </summary>
        public virtual Guid TaskItemGuid { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 任务名称
        /// </summary>
        public virtual string TaskItemName { get; set; }
        /// <summary>
        /// 旧任务名称
        /// </summary>
        public virtual string TaskItemOldName { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        public virtual DateTime? BeginDate { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        public virtual DateTime? EndDate { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// 状态：0正常；1已删除到回收站；2彻底删除
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 隶属于：0自己；1团队；
        /// </summary>
        public virtual int BelongTo { get; set; }
        /// <summary>
        /// 可见范围：0自己可见（本团队可见）；1本团队和上级可见；2全公司可见；
        /// </summary>
        public virtual int VisibleRange { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Team table.
    /// </summary>
	[Table("Team")]
	public partial class Team
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long TeamId { get; set; }
        /// <summary>
        /// 父Id
        /// </summary>
        public virtual long ParentId { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 树路径：多个用逗号间隔
        /// </summary>
        public virtual string ParentIds { get; set; }
        /// <summary>
        /// 类型：1部门；2项目；3群组；4任务
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 组织架构Id、项目Id、群组Id、任务Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 组织架构Guid、项目Guid、群组Guid、任务Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 部门名称；项目名称；群组名称；任务名称
        /// </summary>
        public virtual string ObjectName { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public virtual int Sorting { get; set; }
        /// <summary>
        /// 层级
        /// </summary>
        public virtual int Depth { get; set; }
        /// <summary>
        /// 状态：1正常；2删除到回收站；3彻底删除
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Topic table.
    /// </summary>
	[Table("Topic")]
	public partial class Topic
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long TopicId { get; set; }
        /// <summary>
        /// 主键Guid
        /// </summary>
        public virtual Guid TopicGuid { get; set; }
        /// <summary>
        /// 类型：1部门；2项目；3群组；4任务；5话题；6用户；7日程；8文件；
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 组织架构Id、项目Id、群组Id、任务Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 组织架构Guid、项目Guid、群组Guid、任务Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 标题
        /// </summary>
        public virtual string TopicTitle { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public virtual string TopicContent { get; set; }
        /// <summary>
        /// 艾特人，多个用逗号间隔
        /// </summary>
        public virtual string AtUserId { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TeamMember table.
    /// </summary>
	[Table("TeamMember")]
	public partial class TeamMember
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long TeamMemberId { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 1组织部门、2项目；3群组；4任务
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 组织架构Id、项目Id、群组Id、任务Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 组织架构Guid、项目Guid、群组Guid、任务Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 关联的用户
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// RoleType表Id
        /// </summary>
        public virtual int RoleTypeId { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DailyScheduleMember table.
    /// </summary>
	[Table("DailyScheduleMember")]
	public partial class DailyScheduleMember
	{
        /// <summary>
        /// 日程参与人主键
        /// </summary>
        [Key]
        public virtual long DailyScheduleMemberId { get; set; }
        /// <summary>
        /// 日程ID
        /// </summary>
        public virtual long? DailyScheduleId { get; set; }
        /// <summary>
        /// 参与人
        /// </summary>
        public virtual long? UserId { get; set; }
        /// <summary>
        /// 创建人ID
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Comments table.
    /// </summary>
	[Table("Comments")]
	public partial class Comment
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long CommentId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 容器ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 容器Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 父级ID
        /// </summary>
        public virtual long ParentId { get; set; }
        /// <summary>
        /// 评论路径 多个以,分隔
        /// </summary>
        public virtual string ParentIds { get; set; }
        /// <summary>
        /// 层级 默认1
        /// </summary>
        public virtual int Depth { get; set; }
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 评论人用户ID
        /// </summary>
        public virtual string CommentContent { get; set; }
        /// <summary>
        /// 评论内容
        /// </summary>
        public virtual string AtUserId { get; set; }
        /// <summary>
        /// 艾特谁 多个用户Id以,分隔
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// 是否删除 0:否 1:是 默认0
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the OftenObject table.
    /// </summary>
	[Table("OftenObject")]
	public partial class OftenObject
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long OftenObjectId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// 容器ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 容器Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the AttachmentTeam table.
    /// </summary>
	[Table("AttachmentTeam")]
	public partial class AttachmentTeam
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long AttachmentTeamId { get; set; }
        /// <summary>
        /// 1组织架构；2项目；3群组；4任务
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 组织架构Id、项目Id、群组Id、任务Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 组织架构Guid、项目Guid、群组Guid、任务Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 附件Id
        /// </summary>
        public virtual Guid AttachmentId { get; set; }
        public virtual long CreateUserId { get; set; }
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ObjectTop table.
    /// </summary>
	[Table("ObjectTop")]
	public partial class ObjectTop
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long ObjectTopId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// 容器ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 容器Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the AttitudesType table.
    /// </summary>
	[Table("AttitudesType")]
	public partial class AttitudesType
	{
        /// <summary>
        /// 态度类型ID
        /// </summary>
        [Key]
        public virtual int AttitudesTypeId { get; set; }
        /// <summary>
        /// 态度类型名称
        /// </summary>
        public virtual string AttitudesTypeName { get; set; }
        /// <summary>
        /// 态度类型图标
        /// </summary>
        public virtual string AttitudesTypeImage { get; set; }
        /// <summary>
        /// 是否可用 0:不可用 1可用 默认1
        /// </summary>
        public virtual bool IsEnable { get; set; }
	}

    /// <summary>
    /// A class which represents the UserCompany table.
    /// </summary>
	[Table("UserCompany")]
	public partial class UserCompany
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long UserCompanyId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 状态（0正常，启用；1锁定，禁用）
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
	}

    /// <summary>
    /// A class which represents the UserFocus table.
    /// </summary>
	[Table("UserFocus")]
	public partial class UserFocu
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long UserFocusId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// 类型：1部门；2项目；3群组；4任务；5话题；6用户
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 对象GUID
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 对象ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 是否隐藏动态
        /// </summary>
        public virtual bool IsHide { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Tag table.
    /// </summary>
	[Table("Tag")]
	public partial class Tag
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long TagId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 标签组ID
        /// </summary>
        public virtual long TagGroupId { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 标签名称
        /// </summary>
        public virtual string TagName { get; set; }
        /// <summary>
        /// 标签描述
        /// </summary>
        public virtual string TagDescription { get; set; }
        /// <summary>
        /// 标签样式
        /// </summary>
        public virtual string TagStyle { get; set; }
        /// <summary>
        /// 是否删除 0:否 1:是 默认0
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the LoginLog table.
    /// </summary>
	[Table("LoginLog")]
	public partial class LoginLog
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long LoginId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual int CompanyId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual string UserId { get; set; }
        /// <summary>
        /// 登录类型（1PC密码，2PC扫码，3微信）
        /// </summary>
        public virtual int LoginType { get; set; }
        /// <summary>
        /// 用户IP
        /// </summary>
        public virtual string UserIP { get; set; }
        /// <summary>
        /// 操作系统信息
        /// </summary>
        public virtual string OsInfo { get; set; }
        /// <summary>
        /// 浏览器
        /// </summary>
        public virtual string Browser { get; set; }
        /// <summary>
        /// 消息
        /// </summary>
        public virtual string Message { get; set; }
        /// <summary>
        /// 原因
        /// </summary>
        public virtual string Reason { get; set; }
        /// <summary>
        /// 终端设备
        /// </summary>
        public virtual string TagEquipment { get; set; }
        /// <summary>
        /// UserAgent
        /// </summary>
        public virtual string UserAgent { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Company table.
    /// </summary>
	[Table("Company")]
	public partial class Company
	{
        /// <summary>
        /// 公司ID
        /// </summary>
        [Key]
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 公司名
        /// </summary>
        public virtual string CompanyName { get; set; }
        /// <summary>
        /// 公司地址
        /// </summary>
        public virtual string Address { get; set; }
        /// <summary>
        /// 公司联系电话
        /// </summary>
        public virtual string Phone { get; set; }
        /// <summary>
        /// 公司联系人姓名
        /// </summary>
        public virtual string Linkman { get; set; }
        /// <summary>
        /// 邮箱后缀
        /// </summary>
        public virtual string EmailSuffix { get; set; }
        /// <summary>
        /// 公司logo
        /// </summary>
        public virtual string Logo { get; set; }
        /// <summary>
        /// 状态（0正常，启用；1锁定，禁用）
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// 更新人
        /// </summary>
        public virtual long? UpdateUserId { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TagGroup table.
    /// </summary>
	[Table("TagGroup")]
	public partial class TagGroup
	{
        /// <summary>
        /// 标签组ID
        /// </summary>
        [Key]
        public virtual long TagGroupId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 标签组名称
        /// </summary>
        public virtual string TagGroupName { get; set; }
        /// <summary>
        /// 标签组描述
        /// </summary>
        public virtual string TagGroupDescription { get; set; }
        /// <summary>
        /// 是否删除 0:否 1:是
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the CompanyInviteCode table.
    /// </summary>
	[Table("CompanyInviteCode")]
	public partial class CompanyInviteCode
	{
        /// <summary>
        /// 邀请码ID
        /// </summary>
        [Key]
        public virtual Guid CompanyInviteCodeId { get; set; }
        /// <summary>
        /// 邀请的companyId
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 超期时间(失效时间)
        /// </summary>
        public virtual DateTime ExpireDate { get; set; }
        /// <summary>
        /// 创建人ID
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Organization table.
    /// </summary>
	[Table("Organization")]
	public partial class Organization
	{
        /// <summary>
        /// 主键Id
        /// </summary>
        [Key]
        public virtual long OrganizationId { get; set; }
        /// <summary>
        /// 主键Guid
        /// </summary>
        public virtual Guid OrganizationGuid { get; set; }
        /// <summary>
        /// 名称
        /// </summary>
        public virtual string OrganizationName { get; set; }
        /// <summary>
        /// 原名称
        /// </summary>
        public virtual string OrganizationOldName { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 排序
        /// </summary>
        public virtual int Sorting { get; set; }
        /// <summary>
        /// 级别
        /// </summary>
        public virtual int Depth { get; set; }
        /// <summary>
        /// 状态（0正常，启用；1停用，禁用）
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// 最近更新人
        /// </summary>
        public virtual long? UpdateUserId { get; set; }
        /// <summary>
        /// 最近更新时间
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ChangeHistory table.
    /// </summary>
	[Table("ChangeHistory")]
	public partial class ChangeHistory
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long ChangeHistoryId { get; set; }
        /// <summary>
        /// 容器ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 容器Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 变更类型 1:姓名
        /// </summary>
        public virtual int ChangeTypeId { get; set; }
        /// <summary>
        /// 变更前
        /// </summary>
        public virtual string BeforeChange { get; set; }
        /// <summary>
        /// 变更后
        /// </summary>
        public virtual string AfterChange { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the User table.
    /// </summary>
	[Table("User")]
	public partial class User
	{
        /// <summary>
        /// 用户ID
        /// </summary>
        [Key]
        public virtual long UserId { get; set; }
        /// <summary>
        /// 中文名
        /// </summary>
        public virtual string ChnName { get; set; }
        /// <summary>
        /// 英文名
        /// </summary>
        public virtual string EngName { get; set; }
        /// <summary>
        /// 邮箱
        /// </summary>
        public virtual string Email { get; set; }
        /// <summary>
        /// 移动电话
        /// </summary>
        public virtual string PhoneNumber { get; set; }
        /// <summary>
        /// 固定电话
        /// </summary>
        public virtual string TelephoneNumber { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        public virtual string Password { get; set; }
        /// <summary>
        /// 状态（0正常，启用；1锁定，禁用）
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 性别(1男2女)
        /// </summary>
        public virtual int? Gender { get; set; }
        /// <summary>
        /// 地址
        /// </summary>
        public virtual string Address { get; set; }
        /// <summary>
        /// 小头像
        /// </summary>
        public virtual string AvatarSmall { get; set; }
        /// <summary>
        /// 中头像
        /// </summary>
        public virtual string AvatarMiddle { get; set; }
        /// <summary>
        /// 大头像
        /// </summary>
        public virtual string AvatarBig { get; set; }
        /// <summary>
        /// 头像原图
        /// </summary>
        public virtual string AvatarOriginal { get; set; }
        /// <summary>
        /// qq号码
        /// </summary>
        public virtual long? QQ { get; set; }
        /// <summary>
        /// 微博名
        /// </summary>
        public virtual string WeiBo { get; set; }
        /// <summary>
        /// linkedin
        /// </summary>
        public virtual string LinkedIn { get; set; }
        /// <summary>
        /// 微信名
        /// </summary>
        public virtual string WeChatName { get; set; }
        /// <summary>
        /// 微信昵称
        /// </summary>
        public virtual string WeChatNick { get; set; }
        /// <summary>
        /// 出生日期
        /// </summary>
        public virtual DateTime? Birthdate { get; set; }
        /// <summary>
        /// 注册时间
        /// </summary>
        public virtual DateTime? RegistTime { get; set; }
        /// <summary>
        /// 是否激活
        /// </summary>
        public virtual bool IsActive { get; set; }
        /// <summary>
        /// 注册code
        /// </summary>
        public virtual string RegCode { get; set; }
        /// <summary>
        /// 重置code
        /// </summary>
        public virtual string ResetCode { get; set; }
        /// <summary>
        /// unionid
        /// </summary>
        public virtual string UnionId { get; set; }
        /// <summary>
        /// 开放平台openid
        /// </summary>
        public virtual string OpenPlatformOpenId { get; set; }
        /// <summary>
        /// 公众平台openid
        /// </summary>
        public virtual string WechatOpenId { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the UserOrganization table.
    /// </summary>
	[Table("UserOrganization")]
	public partial class UserOrganization
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long UserOrganizationId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// 组织ID
        /// </summary>
        public virtual long OrganizationId { get; set; }
        /// <summary>
        /// 组织GUID
        /// </summary>
        public virtual Guid OrganizationGuid { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Position table.
    /// </summary>
	[Table("Position")]
	public partial class Position
	{
        /// <summary>
        /// 岗位ID
        /// </summary>
        [Key]
        public virtual long PositionId { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 岗位名称
        /// </summary>
        public virtual string PositionName { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public virtual string Remark { get; set; }
        /// <summary>
        /// 状态(0启用,1禁用)
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// 更新人
        /// </summary>
        public virtual long? UpdateUserId { get; set; }
        /// <summary>
        /// 更新时间
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the UserPosition table.
    /// </summary>
	[Table("UserPosition")]
	public partial class UserPosition
	{
        /// <summary>
        /// 主键
        /// </summary>
        [Key]
        public virtual long UserPositionId { get; set; }
        /// <summary>
        /// 公司ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 用户ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// 组织ID
        /// </summary>
        public virtual long OrganizationId { get; set; }
        /// <summary>
        /// 岗位ID
        /// </summary>
        public virtual long PositionId { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DailySchedule table.
    /// </summary>
	[Table("DailySchedule")]
	public partial class DailySchedule
	{
        /// <summary>
        /// 日程ID
        /// </summary>
        [Key]
        public virtual long DailyScheduleId { get; set; }
        /// <summary>
        /// 公司Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 对象类型id
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 对象ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 对象GUID
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 日程名称
        /// </summary>
        public virtual string DailyScheduleName { get; set; }
        /// <summary>
        /// 原名称
        /// </summary>
        public virtual string DailyScheduleOldName { get; set; }
        /// <summary>
        /// 开始时间
        /// </summary>
        public virtual DateTime? BeginTime { get; set; }
        /// <summary>
        /// 结束时间
        /// </summary>
        public virtual DateTime? EndTime { get; set; }
        /// <summary>
        /// 描述
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// 是否全天
        /// </summary>
        public virtual bool? IsAllDate { get; set; }
        /// <summary>
        /// 提醒时间
        /// </summary>
        public virtual DateTime? ReminderTime { get; set; }
        /// <summary>
        /// 是否循环提醒
        /// </summary>
        public virtual bool? IsCycle { get; set; }
        /// <summary>
        /// 0未开始，1进行中，2已完成
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 是否可用
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ObjectTag table.
    /// </summary>
	[Table("ObjectTag")]
	public partial class ObjectTag
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long ObjectTagId { get; set; }
        /// <summary>
        /// 标签ID
        /// </summary>
        public virtual long TagId { get; set; }
        /// <summary>
        /// 容器ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 容器Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProjectTemplate table.
    /// </summary>
	[Table("ProjectTemplate")]
	public partial class ProjectTemplate
	{
        /// <summary>
        /// 模板主键
        /// </summary>
        [Key]
        public virtual long TemplateId { get; set; }
        /// <summary>
        /// 模板类型（0系统，1用户）
        /// </summary>
        public virtual byte TemplateType { get; set; }
        /// <summary>
        /// 模板名称
        /// </summary>
        public virtual string TemplateName { get; set; }
        /// <summary>
        /// 模板对象
        /// </summary>
        public virtual string TemplateJson { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public virtual string Remark { get; set; }
        /// <summary>
        /// 模板拥有者
        /// </summary>
        public virtual long BelongUserId { get; set; }
        /// <summary>
        /// 状态
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// 创建人
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DynamicNotices table.
    /// </summary>
	[Table("DynamicNotices")]
	public partial class DynamicNotice
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long DynamicNoticesId { get; set; }
        /// <summary>
        /// 动态发起人Id
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// 动态Id
        /// </summary>
        public virtual long DynamicMsgId { get; set; }
        /// <summary>
        /// 动态接收人Id
        /// </summary>
        public virtual long ReceiverUserId { get; set; }
        /// <summary>
        /// 显示区域 （1.个人工作台 2.项目 3.群组 4.部门）
        /// </summary>
        public virtual int DynamicShowArea { get; set; }
        /// <summary>
        /// 是否已读 0:未读 1:已读 默认0
        /// </summary>
        public virtual bool IsRead { get; set; }
        /// <summary>
        /// 是否有效 0:无效 1:有效 默认1
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// 是否推送 0:不推送 1:推送 默认1
        /// </summary>
        public virtual bool IsPush { get; set; }
        /// <summary>
        /// 读取时间
        /// </summary>
        public virtual DateTime? ReadDate { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Attitudes table.
    /// </summary>
	[Table("Attitudes")]
	public partial class Attitude
	{
        /// <summary>
        /// 自增ID
        /// </summary>
        [Key]
        public virtual long AttitudesId { get; set; }
        /// <summary>
        /// 对象类型ID
        /// </summary>
        public virtual long ObjectTypeId { get; set; }
        /// <summary>
        /// 容器Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// 容器Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// 态度类型Id
        /// </summary>
        public virtual int AttitudesTypeId { get; set; }
        /// <summary>
        /// 数量
        /// </summary>
        public virtual int Number { get; set; }
	}

}
