--DbName是数据库名

ALTER DATABASE DbName SET RECOVERY SIMPLE WITH NO_WAIT
ALTER DATABASE DbName SET RECOVERY SIMPLE   --简单模式
DBCC SHRINKFILE (N'DbName_Log' , 1, TRUNCATEONLY)   --数据库文件逻辑名称；1是大小1M
ALTER DATABASE DbName SET RECOVERY FULL WITH NO_WAIT
ALTER DATABASE DbName SET RECOVERY FULL  --还原为完全模式