// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DefaultConnectionString`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=;uid=;pwd=;database=;Connection Timeout=5;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace WeProject.Entity
{
    /// <summary>
    /// A class which represents the Attachment table.
    /// </summary>
	[Table("Attachment")]
	public partial class Attachment
	{
        /// <summary>
        /// ����Guid
        /// </summary>
        [Key]
        public virtual Guid AttachmentId { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// �ļ�����201709
        /// </summary>
        public virtual string Folder { get; set; }
        /// <summary>
        /// �ļ�����
        /// </summary>
        public virtual string Title { get; set; }
        /// <summary>
        /// Դ�ļ���С
        /// </summary>
        public virtual long SizeOriginal { get; set; }
        /// <summary>
        /// С����ͼ��С
        /// </summary>
        public virtual long SizeSmall { get; set; }
        /// <summary>
        /// ������ͼ��С
        /// </summary>
        public virtual long SizeBig { get; set; }
        /// <summary>
        /// �ļ���չ��
        /// </summary>
        public virtual string FileExt { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual int Downloads { get; set; }
        /// <summary>
        /// ״̬��0�ϴ��ļ�����24Сʱ��ɾ������1���õ��ļ���2��־Ϊ�������ļ�������ϵͳ�ļ�������ɾ����
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DynamicMsg table.
    /// </summary>
	[Table("DynamicMsg")]
	public partial class DynamicMsg
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long DynamicMsgId { get; set; }
        /// <summary>
        /// 1��֯�ܹ���2��Ŀ��3Ⱥ�飻4����
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Id����ĿId��Ⱥ��Id������Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Guid����ĿGuid��Ⱥ��Guid������Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ��̬��Ϣ����
        /// </summary>
        public virtual int DynamicMsgTypeId { get; set; }
        /// <summary>
        /// ��ϢժҪ
        /// </summary>
        public virtual string JsonSummary { get; set; }
        /// <summary>
        /// ��Ϣ����
        /// </summary>
        public virtual string JsonDetail { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DynamicMsgType table.
    /// </summary>
	[Table("DynamicMsgType")]
	public partial class DynamicMsgType
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual int DynamicMsgTypeId { get; set; }
        /// <summary>
        /// 1��֯�ܹ���2��Ŀ��3Ⱥ�飻4����
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��̬��Ϣ��������
        /// </summary>
        public virtual string DynamicMsgTypeName { get; set; }
	}

    /// <summary>
    /// A class which represents the Group table.
    /// </summary>
	[Table("Group")]
	public partial class Group
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long GroupId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid GroupGuid { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string GroupName { get; set; }
        /// <summary>
        /// �޸�ǰ����
        /// </summary>
        public virtual string GroupOldName { get; set; }
        /// <summary>
        /// ״̬��0������1��ɾ��������վ��2����ɾ��
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// �����ڣ�0�Լ���1�Ŷӣ�
        /// </summary>
        public virtual int BelongTo { get; set; }
        /// <summary>
        /// �ɼ���Χ��0�Լ��ɼ������Ŷӿɼ�����1���ŶӺ��ϼ��ɼ���2ȫ��˾�ɼ���
        /// </summary>
        public virtual int VisibleRange { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ObjectType table.
    /// </summary>
	[Table("ObjectType")]
	public partial class ObjectType
	{
        /// <summary>
        /// 1��֯�ܹ���2��Ŀ��3Ⱥ�飻4����
        /// </summary>
        [Key]
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��������
        /// </summary>
        public virtual string ObjectTypeName { get; set; }
	}

    /// <summary>
    /// A class which represents the Project table.
    /// </summary>
	[Table("Project")]
	public partial class Project
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long ProjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ProjectGuid { get; set; }
        /// <summary>
        /// ��˾
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��Ŀ����
        /// </summary>
        public virtual string ProjectName { get; set; }
        /// <summary>
        /// �޸�ǰ����
        /// </summary>
        public virtual string ProjectOldName { get; set; }
        /// <summary>
        /// ��ʼ����
        /// </summary>
        public virtual DateTime? BeginDate { get; set; }
        /// <summary>
        /// ��������
        /// </summary>
        public virtual DateTime? EndDate { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// ״̬��0������1��ɾ��������վ��2����ɾ��
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// �����ڣ�0�Լ���1�Ŷӣ�
        /// </summary>
        public virtual int BelongTo { get; set; }
        /// <summary>
        /// �ɼ���Χ��0�Լ��ɼ������Ŷӿɼ�����1���ŶӺ��ϼ��ɼ���2ȫ��˾�ɼ���
        /// </summary>
        public virtual int VisibleRange { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the RoleType table.
    /// </summary>
	[Table("RoleType")]
	public partial class RoleType
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual int RoleTypeId { get; set; }
        /// <summary>
        /// ��ɫ����
        /// </summary>
        public virtual string RoleTypeName { get; set; }
        /// <summary>
        /// ��ɫ���
        /// </summary>
        public virtual string RoleTypeShortName { get; set; }
        /// <summary>
        /// ��ɫ����
        /// </summary>
        public virtual string RoleTypeDescription { get; set; }
	}

    /// <summary>
    /// A class which represents the TaskItem table.
    /// </summary>
	[Table("TaskItem")]
	public partial class TaskItem
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long TaskItemId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid TaskItemGuid { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��������
        /// </summary>
        public virtual string TaskItemName { get; set; }
        /// <summary>
        /// ����������
        /// </summary>
        public virtual string TaskItemOldName { get; set; }
        /// <summary>
        /// ��ʼʱ��
        /// </summary>
        public virtual DateTime? BeginDate { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime? EndDate { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// ״̬��0������1��ɾ��������վ��2����ɾ��
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// �����ڣ�0�Լ���1�Ŷӣ�
        /// </summary>
        public virtual int BelongTo { get; set; }
        /// <summary>
        /// �ɼ���Χ��0�Լ��ɼ������Ŷӿɼ�����1���ŶӺ��ϼ��ɼ���2ȫ��˾�ɼ���
        /// </summary>
        public virtual int VisibleRange { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Team table.
    /// </summary>
	[Table("Team")]
	public partial class Team
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long TeamId { get; set; }
        /// <summary>
        /// ��Id
        /// </summary>
        public virtual long ParentId { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��·��������ö��ż��
        /// </summary>
        public virtual string ParentIds { get; set; }
        /// <summary>
        /// ���ͣ�1���ţ�2��Ŀ��3Ⱥ�飻4����
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Id����ĿId��Ⱥ��Id������Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Guid����ĿGuid��Ⱥ��Guid������Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// �������ƣ���Ŀ���ƣ�Ⱥ�����ƣ���������
        /// </summary>
        public virtual string ObjectName { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual int Sorting { get; set; }
        /// <summary>
        /// �㼶
        /// </summary>
        public virtual int Depth { get; set; }
        /// <summary>
        /// ״̬��1������2ɾ��������վ��3����ɾ��
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Topic table.
    /// </summary>
	[Table("Topic")]
	public partial class Topic
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long TopicId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid TopicGuid { get; set; }
        /// <summary>
        /// ���ͣ�1���ţ�2��Ŀ��3Ⱥ�飻4����5���⣻6�û���7�ճ̣�8�ļ���
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Id����ĿId��Ⱥ��Id������Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Guid����ĿGuid��Ⱥ��Guid������Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string TopicTitle { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string TopicContent { get; set; }
        /// <summary>
        /// �����ˣ�����ö��ż��
        /// </summary>
        public virtual string AtUserId { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TeamMember table.
    /// </summary>
	[Table("TeamMember")]
	public partial class TeamMember
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long TeamMemberId { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// 1��֯���š�2��Ŀ��3Ⱥ�飻4����
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Id����ĿId��Ⱥ��Id������Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Guid����ĿGuid��Ⱥ��Guid������Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// �������û�
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// RoleType��Id
        /// </summary>
        public virtual int RoleTypeId { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DailyScheduleMember table.
    /// </summary>
	[Table("DailyScheduleMember")]
	public partial class DailyScheduleMember
	{
        /// <summary>
        /// �ճ̲���������
        /// </summary>
        [Key]
        public virtual long DailyScheduleMemberId { get; set; }
        /// <summary>
        /// �ճ�ID
        /// </summary>
        public virtual long? DailyScheduleId { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long? UserId { get; set; }
        /// <summary>
        /// ������ID
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ��������
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Comments table.
    /// </summary>
	[Table("Comments")]
	public partial class Comment
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long CommentId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ParentId { get; set; }
        /// <summary>
        /// ����·�� �����,�ָ�
        /// </summary>
        public virtual string ParentIds { get; set; }
        /// <summary>
        /// �㼶 Ĭ��1
        /// </summary>
        public virtual int Depth { get; set; }
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// �������û�ID
        /// </summary>
        public virtual string CommentContent { get; set; }
        /// <summary>
        /// ��������
        /// </summary>
        public virtual string AtUserId { get; set; }
        /// <summary>
        /// ����˭ ����û�Id��,�ָ�
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// �Ƿ�ɾ�� 0:�� 1:�� Ĭ��0
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the OftenObject table.
    /// </summary>
	[Table("OftenObject")]
	public partial class OftenObject
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long OftenObjectId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the AttachmentTeam table.
    /// </summary>
	[Table("AttachmentTeam")]
	public partial class AttachmentTeam
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long AttachmentTeamId { get; set; }
        /// <summary>
        /// 1��֯�ܹ���2��Ŀ��3Ⱥ�飻4����
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Id����ĿId��Ⱥ��Id������Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ��֯�ܹ�Guid����ĿGuid��Ⱥ��Guid������Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ����Id
        /// </summary>
        public virtual Guid AttachmentId { get; set; }
        public virtual long CreateUserId { get; set; }
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ObjectTop table.
    /// </summary>
	[Table("ObjectTop")]
	public partial class ObjectTop
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long ObjectTopId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the AttitudesType table.
    /// </summary>
	[Table("AttitudesType")]
	public partial class AttitudesType
	{
        /// <summary>
        /// ̬������ID
        /// </summary>
        [Key]
        public virtual int AttitudesTypeId { get; set; }
        /// <summary>
        /// ̬����������
        /// </summary>
        public virtual string AttitudesTypeName { get; set; }
        /// <summary>
        /// ̬������ͼ��
        /// </summary>
        public virtual string AttitudesTypeImage { get; set; }
        /// <summary>
        /// �Ƿ���� 0:������ 1���� Ĭ��1
        /// </summary>
        public virtual bool IsEnable { get; set; }
	}

    /// <summary>
    /// A class which represents the UserCompany table.
    /// </summary>
	[Table("UserCompany")]
	public partial class UserCompany
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long UserCompanyId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ״̬��0���������ã�1���������ã�
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
	}

    /// <summary>
    /// A class which represents the UserFocus table.
    /// </summary>
	[Table("UserFocus")]
	public partial class UserFocu
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long UserFocusId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// ���ͣ�1���ţ�2��Ŀ��3Ⱥ�飻4����5���⣻6�û�
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ����GUID
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// �Ƿ����ض�̬
        /// </summary>
        public virtual bool IsHide { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Tag table.
    /// </summary>
	[Table("Tag")]
	public partial class Tag
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long TagId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��ǩ��ID
        /// </summary>
        public virtual long TagGroupId { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��ǩ����
        /// </summary>
        public virtual string TagName { get; set; }
        /// <summary>
        /// ��ǩ����
        /// </summary>
        public virtual string TagDescription { get; set; }
        /// <summary>
        /// ��ǩ��ʽ
        /// </summary>
        public virtual string TagStyle { get; set; }
        /// <summary>
        /// �Ƿ�ɾ�� 0:�� 1:�� Ĭ��0
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the LoginLog table.
    /// </summary>
	[Table("LoginLog")]
	public partial class LoginLog
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long LoginId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual int CompanyId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual string UserId { get; set; }
        /// <summary>
        /// ��¼���ͣ�1PC���룬2PCɨ�룬3΢�ţ�
        /// </summary>
        public virtual int LoginType { get; set; }
        /// <summary>
        /// �û�IP
        /// </summary>
        public virtual string UserIP { get; set; }
        /// <summary>
        /// ����ϵͳ��Ϣ
        /// </summary>
        public virtual string OsInfo { get; set; }
        /// <summary>
        /// �����
        /// </summary>
        public virtual string Browser { get; set; }
        /// <summary>
        /// ��Ϣ
        /// </summary>
        public virtual string Message { get; set; }
        /// <summary>
        /// ԭ��
        /// </summary>
        public virtual string Reason { get; set; }
        /// <summary>
        /// �ն��豸
        /// </summary>
        public virtual string TagEquipment { get; set; }
        /// <summary>
        /// UserAgent
        /// </summary>
        public virtual string UserAgent { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Company table.
    /// </summary>
	[Table("Company")]
	public partial class Company
	{
        /// <summary>
        /// ��˾ID
        /// </summary>
        [Key]
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��˾��
        /// </summary>
        public virtual string CompanyName { get; set; }
        /// <summary>
        /// ��˾��ַ
        /// </summary>
        public virtual string Address { get; set; }
        /// <summary>
        /// ��˾��ϵ�绰
        /// </summary>
        public virtual string Phone { get; set; }
        /// <summary>
        /// ��˾��ϵ������
        /// </summary>
        public virtual string Linkman { get; set; }
        /// <summary>
        /// �����׺
        /// </summary>
        public virtual string EmailSuffix { get; set; }
        /// <summary>
        /// ��˾logo
        /// </summary>
        public virtual string Logo { get; set; }
        /// <summary>
        /// ״̬��0���������ã�1���������ã�
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long? UpdateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the TagGroup table.
    /// </summary>
	[Table("TagGroup")]
	public partial class TagGroup
	{
        /// <summary>
        /// ��ǩ��ID
        /// </summary>
        [Key]
        public virtual long TagGroupId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ��ǩ������
        /// </summary>
        public virtual string TagGroupName { get; set; }
        /// <summary>
        /// ��ǩ������
        /// </summary>
        public virtual string TagGroupDescription { get; set; }
        /// <summary>
        /// �Ƿ�ɾ�� 0:�� 1:��
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the CompanyInviteCode table.
    /// </summary>
	[Table("CompanyInviteCode")]
	public partial class CompanyInviteCode
	{
        /// <summary>
        /// ������ID
        /// </summary>
        [Key]
        public virtual Guid CompanyInviteCodeId { get; set; }
        /// <summary>
        /// �����companyId
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ����ʱ��(ʧЧʱ��)
        /// </summary>
        public virtual DateTime ExpireDate { get; set; }
        /// <summary>
        /// ������ID
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Organization table.
    /// </summary>
	[Table("Organization")]
	public partial class Organization
	{
        /// <summary>
        /// ����Id
        /// </summary>
        [Key]
        public virtual long OrganizationId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid OrganizationGuid { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string OrganizationName { get; set; }
        /// <summary>
        /// ԭ����
        /// </summary>
        public virtual string OrganizationOldName { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual int Sorting { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual int Depth { get; set; }
        /// <summary>
        /// ״̬��0���������ã�1ͣ�ã����ã�
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// ���������
        /// </summary>
        public virtual long? UpdateUserId { get; set; }
        /// <summary>
        /// �������ʱ��
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ChangeHistory table.
    /// </summary>
	[Table("ChangeHistory")]
	public partial class ChangeHistory
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long ChangeHistoryId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ������� 1:����
        /// </summary>
        public virtual int ChangeTypeId { get; set; }
        /// <summary>
        /// ���ǰ
        /// </summary>
        public virtual string BeforeChange { get; set; }
        /// <summary>
        /// �����
        /// </summary>
        public virtual string AfterChange { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the User table.
    /// </summary>
	[Table("User")]
	public partial class User
	{
        /// <summary>
        /// �û�ID
        /// </summary>
        [Key]
        public virtual long UserId { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual string ChnName { get; set; }
        /// <summary>
        /// Ӣ����
        /// </summary>
        public virtual string EngName { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string Email { get; set; }
        /// <summary>
        /// �ƶ��绰
        /// </summary>
        public virtual string PhoneNumber { get; set; }
        /// <summary>
        /// �̶��绰
        /// </summary>
        public virtual string TelephoneNumber { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string Password { get; set; }
        /// <summary>
        /// ״̬��0���������ã�1���������ã�
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// �Ա�(1��2Ů)
        /// </summary>
        public virtual int? Gender { get; set; }
        /// <summary>
        /// ��ַ
        /// </summary>
        public virtual string Address { get; set; }
        /// <summary>
        /// Сͷ��
        /// </summary>
        public virtual string AvatarSmall { get; set; }
        /// <summary>
        /// ��ͷ��
        /// </summary>
        public virtual string AvatarMiddle { get; set; }
        /// <summary>
        /// ��ͷ��
        /// </summary>
        public virtual string AvatarBig { get; set; }
        /// <summary>
        /// ͷ��ԭͼ
        /// </summary>
        public virtual string AvatarOriginal { get; set; }
        /// <summary>
        /// qq����
        /// </summary>
        public virtual long? QQ { get; set; }
        /// <summary>
        /// ΢����
        /// </summary>
        public virtual string WeiBo { get; set; }
        /// <summary>
        /// linkedin
        /// </summary>
        public virtual string LinkedIn { get; set; }
        /// <summary>
        /// ΢����
        /// </summary>
        public virtual string WeChatName { get; set; }
        /// <summary>
        /// ΢���ǳ�
        /// </summary>
        public virtual string WeChatNick { get; set; }
        /// <summary>
        /// ��������
        /// </summary>
        public virtual DateTime? Birthdate { get; set; }
        /// <summary>
        /// ע��ʱ��
        /// </summary>
        public virtual DateTime? RegistTime { get; set; }
        /// <summary>
        /// �Ƿ񼤻�
        /// </summary>
        public virtual bool IsActive { get; set; }
        /// <summary>
        /// ע��code
        /// </summary>
        public virtual string RegCode { get; set; }
        /// <summary>
        /// ����code
        /// </summary>
        public virtual string ResetCode { get; set; }
        /// <summary>
        /// unionid
        /// </summary>
        public virtual string UnionId { get; set; }
        /// <summary>
        /// ����ƽ̨openid
        /// </summary>
        public virtual string OpenPlatformOpenId { get; set; }
        /// <summary>
        /// ����ƽ̨openid
        /// </summary>
        public virtual string WechatOpenId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the UserOrganization table.
    /// </summary>
	[Table("UserOrganization")]
	public partial class UserOrganization
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long UserOrganizationId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// ��֯ID
        /// </summary>
        public virtual long OrganizationId { get; set; }
        /// <summary>
        /// ��֯GUID
        /// </summary>
        public virtual Guid OrganizationGuid { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Position table.
    /// </summary>
	[Table("Position")]
	public partial class Position
	{
        /// <summary>
        /// ��λID
        /// </summary>
        [Key]
        public virtual long PositionId { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��λ����
        /// </summary>
        public virtual string PositionName { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// ��ע
        /// </summary>
        public virtual string Remark { get; set; }
        /// <summary>
        /// ״̬(0����,1����)
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long? UpdateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime? UpdateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the UserPosition table.
    /// </summary>
	[Table("UserPosition")]
	public partial class UserPosition
	{
        /// <summary>
        /// ����
        /// </summary>
        [Key]
        public virtual long UserPositionId { get; set; }
        /// <summary>
        /// ��˾ID
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// �û�ID
        /// </summary>
        public virtual long UserId { get; set; }
        /// <summary>
        /// ��֯ID
        /// </summary>
        public virtual long OrganizationId { get; set; }
        /// <summary>
        /// ��λID
        /// </summary>
        public virtual long PositionId { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DailySchedule table.
    /// </summary>
	[Table("DailySchedule")]
	public partial class DailySchedule
	{
        /// <summary>
        /// �ճ�ID
        /// </summary>
        [Key]
        public virtual long DailyScheduleId { get; set; }
        /// <summary>
        /// ��˾Id
        /// </summary>
        public virtual long CompanyId { get; set; }
        /// <summary>
        /// ��������id
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����GUID
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// �ճ�����
        /// </summary>
        public virtual string DailyScheduleName { get; set; }
        /// <summary>
        /// ԭ����
        /// </summary>
        public virtual string DailyScheduleOldName { get; set; }
        /// <summary>
        /// ��ʼʱ��
        /// </summary>
        public virtual DateTime? BeginTime { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime? EndTime { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual string Description { get; set; }
        /// <summary>
        /// �Ƿ�ȫ��
        /// </summary>
        public virtual bool? IsAllDate { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime? ReminderTime { get; set; }
        /// <summary>
        /// �Ƿ�ѭ������
        /// </summary>
        public virtual bool? IsCycle { get; set; }
        /// <summary>
        /// 0δ��ʼ��1�����У�2�����
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// �Ƿ����
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ObjectTag table.
    /// </summary>
	[Table("ObjectTag")]
	public partial class ObjectTag
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long ObjectTagId { get; set; }
        /// <summary>
        /// ��ǩID
        /// </summary>
        public virtual long TagId { get; set; }
        /// <summary>
        /// ����ID
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual int ObjectTypeId { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the ProjectTemplate table.
    /// </summary>
	[Table("ProjectTemplate")]
	public partial class ProjectTemplate
	{
        /// <summary>
        /// ģ������
        /// </summary>
        [Key]
        public virtual long TemplateId { get; set; }
        /// <summary>
        /// ģ�����ͣ�0ϵͳ��1�û���
        /// </summary>
        public virtual byte TemplateType { get; set; }
        /// <summary>
        /// ģ������
        /// </summary>
        public virtual string TemplateName { get; set; }
        /// <summary>
        /// ģ�����
        /// </summary>
        public virtual string TemplateJson { get; set; }
        /// <summary>
        /// ��ע
        /// </summary>
        public virtual string Remark { get; set; }
        /// <summary>
        /// ģ��ӵ����
        /// </summary>
        public virtual long BelongUserId { get; set; }
        /// <summary>
        /// ״̬
        /// </summary>
        public virtual int Status { get; set; }
        /// <summary>
        /// ������
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the DynamicNotices table.
    /// </summary>
	[Table("DynamicNotices")]
	public partial class DynamicNotice
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long DynamicNoticesId { get; set; }
        /// <summary>
        /// ��̬������Id
        /// </summary>
        public virtual long CreateUserId { get; set; }
        /// <summary>
        /// ��̬Id
        /// </summary>
        public virtual long DynamicMsgId { get; set; }
        /// <summary>
        /// ��̬������Id
        /// </summary>
        public virtual long ReceiverUserId { get; set; }
        /// <summary>
        /// ��ʾ���� ��1.���˹���̨ 2.��Ŀ 3.Ⱥ�� 4.���ţ�
        /// </summary>
        public virtual int DynamicShowArea { get; set; }
        /// <summary>
        /// �Ƿ��Ѷ� 0:δ�� 1:�Ѷ� Ĭ��0
        /// </summary>
        public virtual bool IsRead { get; set; }
        /// <summary>
        /// �Ƿ���Ч 0:��Ч 1:��Ч Ĭ��1
        /// </summary>
        public virtual bool IsEnable { get; set; }
        /// <summary>
        /// �Ƿ����� 0:������ 1:���� Ĭ��1
        /// </summary>
        public virtual bool IsPush { get; set; }
        /// <summary>
        /// ��ȡʱ��
        /// </summary>
        public virtual DateTime? ReadDate { get; set; }
        /// <summary>
        /// ����ʱ��
        /// </summary>
        public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the Attitudes table.
    /// </summary>
	[Table("Attitudes")]
	public partial class Attitude
	{
        /// <summary>
        /// ����ID
        /// </summary>
        [Key]
        public virtual long AttitudesId { get; set; }
        /// <summary>
        /// ��������ID
        /// </summary>
        public virtual long ObjectTypeId { get; set; }
        /// <summary>
        /// ����Id
        /// </summary>
        public virtual long ObjectId { get; set; }
        /// <summary>
        /// ����Guid
        /// </summary>
        public virtual Guid ObjectGuid { get; set; }
        /// <summary>
        /// ̬������Id
        /// </summary>
        public virtual int AttitudesTypeId { get; set; }
        /// <summary>
        /// ����
        /// </summary>
        public virtual int Number { get; set; }
	}

}
